"""add_fields_to_submissions

Revision ID: 4c86595acdf7
Revises: c2fc12dfe565
Create Date: 2026-06-28 19:43:07.720849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c86595acdf7'
down_revision: Union[str, Sequence[str], None] = 'c2fc12dfe565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('status', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('verdict', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('detail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'detail')
    op.drop_column('submissions', 'verdict')
    op.drop_column('submissions', 'status')
    # ### end Alembic commands ###
