"""initial

Revision ID: 722c928ac877
Revises: 0b5390fc4502
Create Date: 2026-06-28 18:44:24.547161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722c928ac877'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('language', sa.String(), nullable=False))
    op.add_column('submissions', sa.Column('code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'code')
    op.drop_column('submissions', 'language')
    # ### end Alembic commands ###
